# Generated by Django 2.2.5 on 2019-10-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_minimum_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='hosted_by',
            field=models.CharField(default='', max_length=45),
        ),
    ]
