# Generated by Django 2.2.5 on 2019-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bid_price',
        ),
        migrations.AddField(
            model_name='auction',
            name='new_price',
            field=models.CharField(default=0.0, max_length=50),
        ),
    ]
