# Generated by Django 2.2.5 on 2019-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20191010_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='item_no',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
