# Generated by Django 2.2.5 on 2019-10-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_bidding_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Auction'),
        ),
    ]
