# Generated by Django 2.2.5 on 2019-10-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_bidding_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='item_no',
        ),
    ]
