# Generated by Django 2.2.5 on 2019-11-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_bidding_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
