# Generated by Django 2.2.5 on 2019-11-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auction_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='bid_version',
            field=models.IntegerField(default=0),
        ),
    ]
