# Generated by Django 2.2.5 on 2019-11-09 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_bidding_bid_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
